### ISSUE TITLE
Gold data!

### ISSUE THREAD

**Issue by Anseilon** [Mikeprod/XIV_Databar#12]
![bug](https://cloud.githubusercontent.com/assets/24575895/21202466/61c43696-c21c-11e6-997c-10a079d7142a.jpg)

If you notice, a fresh character has 41c in its bag.  However, the databar reflects it as 0c.

I checked the SavedVariables, and the LUA shows that it is recognizing 41c.  Also, say you have 22s, the module will show it as 22c.  I noticed this was happening until I got an actual gold amount in the bags.  

Didn't see any reports on the matter, as I suppose it really is a minor issue.  Just thought I'd point out the inconsistency!  Thank you for your time!

**Comment by Mikeprod** [comment]
I will look into it tomorrow, thanks for the report.

**Comment by Anseilon** [comment]
Thank -you- for your promptness! <3

**Comment by Mikeprod** [comment]
The fix will be pushed to Curse on the next release.
