### ISSUE TITLE
Option to keep it active during combat

### ISSUE THREAD

**Issue by skmzarn** [Mikeprod/XIV_Databar#13]
I would like the Databar and all its tooltips - everything - to still be functional in combat, exactly like if you weren't in combat. That's it, thanks!

**Comment by Mikeprod** [comment]
I'll see what I can do

**Comment by skmzarn** [comment]
Cool, thanks!

**Comment by Mikeprod** [comment]
A previous release allowed people to chose whether they want to enable the micromenu icons to be interactive during combat.

**Comment by skmzarn** [comment]
Thank you so much for this - it is working perfectly.
