### ISSUE TITLE
Part of screen unavailable

### ISSUE THREAD

**Issue by Legsbiter** [Mikeprod/XIV_Databar#14]
Ever since I updated to 2.0.14, it seems some part of my screen becomes unclickable
![unclickable zone](https://cloud.githubusercontent.com/assets/16323206/21394217/c5fa0a8e-c765-11e6-852b-98ab7b842c9f.png)

See the attached screenshot. I cannot click inside the red circle for some unknown reason.

**Comment by Mikeprod** [comment]
Have you the same problem without all other addons ?

**Comment by Legsbiter** [comment]
I've disabled all my addons one by one and the issue was fixed when I disabled this particular addon.

Weirdly enough, I didn't have this issue back on 2.0.5

**Comment by Mikeprod** [comment]
Uhm ... weird.

**Comment by Legsbiter** [comment]
Yeah, and I'm also not receiving any error messages, that part of my screen is just unclickable for no reason.

**Comment by Mikeprod** [comment]
Do you have the bar at the top or at the bottom ? I can still target players on this part of the screen with the 2.0.14

**Comment by Legsbiter** [comment]
At the bottom

**Comment by Mikeprod** [comment]
Have you reset your addon profile ?

**Comment by Legsbiter** [comment]
Yup, I reseted it and it didn't work. Also tried unchecking every option one by one and it still doesn't work

**Comment by Mikeprod** [comment]
Then I am sorry, so far I really have no clue of what is happening to you ...

**Comment by Legsbiter** [comment]
It's no biggie, the version 2.0.5 is working fine for me. 

Would be great if I had an error message to help you diagnose this issue with but I'm getting none ;/

**Comment by Mikeprod** [comment]
Tbh, I had such kind of issues back to the end of WoD, in addition to keyboard event problems. 
I rainstalled wow and now I still have keyboard issues with the game (with or without addons)

**Comment by Mikeprod** [comment]
Oh and the area you circled it is the place or UI errors such as "I am to far away", "I can't do that now" ... Do you have those errors activated ?

**Comment by Legsbiter** [comment]
About the error messages, yes they're still activated. But it seems the area is bigger than I thought and it's like 20% of my screen from the top.

I'll try fully uninstalling the addons then restart my pc and I'll see from there. (I don't want to reinstall WoW and have to redo my UI)

**Comment by Mikeprod** [comment]
Wth 20% ?!

To keep our UI as it is you just have to save 2 folders : WTF and Interface that's it.

**Comment by Legsbiter** [comment]
Yeah, it's really weird.

I'll try reinstalling my game later during the week and I'll let you know if it helped.

**Comment by Mikeprod** [comment]
OK. Keep me posted ;)

**Comment by Legsbiter** [comment]
Hey, I reinstalled my game and no dice.

I've tried every version up to 2.0.10 and the issue is still there.

The only remarkable difference between 2.0.5 and 2.0.10 I can see is the added option "Fullscreen" in XIV Bar - General option page. Could this be the issue?

**Comment by Legsbiter** [comment]
Nevermind that, I actually found the issue.

Seems to be a conflict with ElvUI and XIV_Databar. Not sure what's causing it right now, I'll look into it.

**Comment by Legsbiter** [comment]
Found the issue, it's somehow in conflict with ElvUI's minimap

**Comment by Mikeprod** [comment]
Thanks for your time finding where the issue comes from. I will see what I can do.

**Comment by Mikeprod** [comment]
I installed ElvUI without any problem with clicks in the indicated area with the last Github version ...

**Comment by Legsbiter** [comment]
Then must be an issue on my side only, I'll have to fresh reinstall my UI since the issue was fixed when I turned off the minimap

**Comment by Legsbiter** [comment]
Welp, found a strange way to fix my issue... Apparently the combo of XIV and my current Elvui created some sort of deadzone to the right of the minimap so I just moved it all the way to the right and now everything is working fine.

**Comment by Mikeprod** [comment]
I do not know the source of the strange thing that happened to you ....

**Comment by Mikeprod** [comment]
Well it appears someone found the origin of the problem. Issue #35 pointed out the source of the problem, identical as what you described. It will be fixed soon.
