### ISSUE TITLE
Talentbar shows no tooltip

### ISSUE THREAD

**Issue by rainmankk** [Mikeprod/XIV_Databar#20]
My Talentbar shows no tooltip. Dont know what to write here more...

**Comment by Mikeprod** [comment]
Uhm ... an error raised in your UI ?

**Comment by rainmankk** [comment]
You have no bugs, yay! <- thats what bugsack is telling me. No errors. It just wont show. With Milles version it worked.

**Comment by Mikeprod** [comment]
Uhm, I don't know, everything is working for me ...

**Comment by Deathevn** [comment]
Maybe it is related. I can't see the talent-tooltip when my vuhdo is at the same position. Seems like the frame-layer of the tooltip isn't in the front of everything.

**Comment by Mikeprod** [comment]
Oh I might see what it is about ! It is because this tooltip is supposed to replace the default game tooltip and there fore if used elsewhere it does not show !

**Comment by Mikeprod** [comment]
I am waiting for any comment about the fix I made. If ok, I'll update Curse !

**Comment by Deathevn** [comment]
Well.. it was late yesterday and I didn't mean the tooltip while hovering (this one is fine) I meant the menu to chose talent/loot-spec. I'm sorry for mixing those two up. The git-version works just fine with the tooltip.

**Comment by Mikeprod** [comment]
Can you please post a screenshot of what happens when you click on the talent module (when you are supposed to see the menu of specs) ?

**Comment by Deathevn** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/1337716/22862999/33b85786-f139-11e6-80d1-d31d63e7c4d0.PNG)

In the bottom left corner you can see the spec-selection-menu hiding behind the vuhdo frame.

**Comment by Mikeprod** [comment]
One solution is for you to change the frame strata of the panels. VuhDo options > Panels Tab > Misc (on the right) and lower the Frame Strata option.

**Comment by Mikeprod** [comment]
I fixed the strata of the menu frames.

**Comment by Deathevn** [comment]
Thanks alot! The git-version works just fine and thanks for letting me know about the vuhdo-setting.
