### ISSUE TITLE
secondary hearthstones sometimes disappear

### ISSUE THREAD

**Issue by Deathevn** [Mikeprod/XIV_Databar#25]
Sometimes the entrance for the secondary hearthstones (dalaran, garrison, ...) just disappears, thus theres only the entrance for the normal hearthstone and next to it the gold entrance. A reloadui solves this issue.

**Comment by Mikeprod** [comment]
I have encountered this issue too. I'll look into it when I have some time.

**Comment by Mikeprod** [comment]
Can you test the git version to confirm the fix I made, because I could not reproduce the issue :(

**Comment by Deathevn** [comment]
I'm using the github-version and it just disappeared again. I'm sorry I'm not sure what triggers this bug.

**Comment by Mikeprod** [comment]
Any feedback appreciated concerning today's update

**Comment by Mikeprod** [comment]
@Deathevn any feedback ? I haven't played that much to note any disappearance.
