### ISSUE TITLE
Messing up Skada

### ISSUE THREAD

**Issue by powntus1838** [Mikeprod/XIV_Databar#26]
I am not 100% sure, but about 90 that the addon somehow messes with Skada. Whenever i've disabled this addon Skada works normally, but not when it's on. For instance, some parts of the screen is not clickable, so I can't see the spells damage, move the Skada window etc. Also, for some weird reason it disappears all the time. This could be a bug in Skada but I don't think so.

**Comment by Mikeprod** [comment]
If I have enough time this week end, I'll dig into this problem.

**Comment by Mikeprod** [comment]
Can you please take a screenshot of you UI to see where your skada is located relatively to the bar ?

**Comment by powntus1838** [comment]
![wowscrnshot_022617_104028](https://cloud.githubusercontent.com/assets/26013853/23338626/21331916-fc10-11e6-80e7-7901513e1e5c.jpg)
The databar is disabled in the picture. I even tried to make to skada window larger, dragging it from the minimap to somewhere around the middle of the screen to see if I could click the spells but that didn't work either. If that's to any help.

**Comment by Mikeprod** [comment]
Have you tried to use only skada and WIV_Databar (without elvui) ?

**Comment by powntus1838** [comment]
Hm, doesn't seem to be any problem when I'm only running xiv and skada.. But I still find it quite weird that Skada works perfectly with every addon enabled except the databar, but once I turn it on it stops working as intentional o.O

**Comment by Mikeprod** [comment]
I hear you. On my end I use Skada and the bar just fine, without elvui ... Maybe disable the elvui skin for skada to see if anything changes ?

**Comment by powntus1838** [comment]
Actually I'm not using the elvui skin for skada. But anyhow, there seems to be some issue with the top left corner, every other corner works just fine when both addons are enabled. I can click my way through skada, move it, resize it etc.. Just not when it's placed in the top left corner no matter how big the window is.. So, if you can't figure out what's causing this, if it even is your addon, i'll just simply move skada :)

**Comment by Mikeprod** [comment]
Ok. It seems therefore a similar problem reported by the issue #14 that I have no clue why it happens. Sorry.

**Comment by powntus1838** [comment]
Well, it doesn't affect my gameplay really was just sort of annoying but I've moved Skada and everything works as usual for now so it's not really game-breaking :)

**Comment by Mikeprod** [comment]
Well it appears someone found the origin of the problem. Issue #35 pointed out the source of the problem, identical as what you described. It will be fixed soon.
