### ISSUE TITLE
Artifact Weapon locked

### ISSUE THREAD

**Issue by marlo94** [Mikeprod/XIV_Databar#30]
XIV blocks the artifact weapon window. When viewing my character page the weapons are greyed out. Same when trying to change the appearance in the Orderhall, you can't see the window.

**Comment by Mikeprod** [comment]
Known issue fixed in the upcoming version on curse please update.

**Comment by marlo94** [comment]
Oh sorry, didn't see the closed issues. My bad.

**Comment by parasemic** [comment]
I updated to the latest version, yet the issue persists

**Comment by Mikeprod** [comment]
Ye I messed up with the artifact lib. Fix coming soon.

**Comment by marlo94** [comment]
Great job, It's fixed now :)
