### ISSUE TITLE
action bar and chat tabs

### ISSUE THREAD

**Issue by the9thresident** [Mikeprod/XIV_Databar#34]
i'm not getting any errors but i've gone through all my addons and disabling this one solved the problems... what happens is this: if i right click my chat tab not only does no menu open but it totally freezes and then another thing happens; i can't click my action bar buttons 1-8 on bars 1 and 2... this also happens sometimes when i try to move spells on around on those buttons... really sad about this cuz i feel that this is pretty much a necessity for any well put together UI...

kitty

**Comment by Mikeprod** [comment]
With only this addon enabled you're having this trouble ?

**Comment by the9thresident** [comment]
sorry... i didn't work that out yet
give me a few days
i'll look at it this weekend
my week has sucked 

kitty

**Comment by the9thresident** [comment]
okay...
with just this addon there is no issue
and with this and Elv i was having no issue either
it's hard to narrow down when there is no error showing up
turned on all my addons and it still worked fine
so, i was all "WTF??!!"
then i remembered i had to remove some stuff that was causing me different issues
so tomorrow i will check the addons i took off with this one enabled to see where the conflict is 
if i can't find it then i'm sorry for posting
however it was disabling this addon that made things work again 
so it has to be two addons that are just not compatible after 7.2
but i'm no coder, so if you think it's something else let me know
i do get an error for this bar when i lvl sometimes though 
i don't think i have it copied down anywhere because i didn't much care about it
if it happens again i will update with the error text

kitty

**Comment by Mikeprod** [comment]
Thanks for your feedback. I haven't had time to look into it, but I will eventually take a look at your problem in couple weeks, I'll be busy this week at least.

**Comment by the9thresident** [comment]
hi there
the problem seems to be with this AddOn and AdiBags 
not any of the plug-ins for AdiBags but just AdiBags and the Config 
together they cause the problem
but disable this AddOn and no more issues 
disable AdiBags and leave this AddOn on and no issues 
so the issue seems to be with running them together 
could be just running them together with Elv?
idk
took me a long time to figure out what old AddOns were not getting along 
that would mean that I change my UI too much lol 

kitty

**Comment by Mikeprod** [comment]
Thank you very much for your tests and feedback, I'll dig into it soon

**Comment by Mikeprod** [comment]
Hey sorry for the delay. Do you still have the issue ? If so could you please screenshot your UI for me to see where your chat is ?

**Comment by Mikeprod** [comment]
Hello, is your issue still happening? Thank you.

**Comment by Mikeprod** [comment]
Please reopen the issue if it's still hapening
