### ISSUE TITLE
[ElvUI] Minimap ClusterFrame

### ISSUE THREAD

**Issue by Merathilis** [Mikeprod/XIV_Databar#35]
Hello,

if you use ElvUI with XIV_Databar and position the MiniMap on the Top Left of your screen the MinimapCluster Frame is all over the top.

So i wonder if you just could use the same code as in ElvUI for the `frame:`

`    MinimapCluster:ClearAllPoints()
    MinimapCluster:SetAllPoints(Minimap)`

Thanks in advanced.

![wowscrnshot_050417_222543](https://cloud.githubusercontent.com/assets/272403/25738912/ce9e2196-317f-11e7-974c-519fa657335a.jpg)

**Comment by Mikeprod** [comment]
You mean when offsetting the top UI or always when the bar is at the top ?

**Comment by Merathilis** [comment]
No, as i wrote. If you position the MiniMap on the Top Left, the MiniMap Cluster (which is an invisible frame) is positon all over the top as you see in the screen. As i looked at your code you reposition the Cluster frame.

**Comment by Mikeprod** [comment]
I only move the Cluster frame when the bar is at the top, otherwise nothing is done to the minimap

**Comment by Merathilis** [comment]
Yeah, buts thats the problem i think, ElvUI set the ClusterFrame to the MiniMap. XIV_Databar position this in  an other way and there get things fucked up. As i say, if you use ElvUI + XIV_Databar and postiton the MiniMap to the top left, you cant't click the area i posted in my Screenshot.

I mean, i don*t care about this cause i don't position the MiniMap on the TopLeft but many ElvUI users complains about this.

**Comment by Mikeprod** [comment]
Oh OK I get it

**Comment by Mikeprod** [comment]
I have pushed a possible fix. I did not test it, because my pc is broken atm. If this git version is ok, let me know so that I can push it to curse. Thanks a lot.

**Comment by Mikeprod** [comment]
It is fixed guys @Merathilis @Legsbiter @powntus1838 please update on curse asap! ;)

**Comment by Merathilis** [comment]
Thanks for the fix, we also changed this a bit in ElvUI. Should be fine now ;)
