### ISSUE TITLE
Buggrabber Bug

### ISSUE THREAD

**Issue by Imiona** [Mikeprod/XIV_Databar#40]
1x XIV_Databar\modules\tradeskill.lua:114: attempt to concatenate field '?' (a nil value)
XIV_Databar\modules\tradeskill.lua:114: in function `StyleTradeskillFrame'
XIV_Databar\modules\tradeskill.lua:79: in function `?'
...dia\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...dia\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...dia\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil

**Comment by Mikeprod** [comment]
How many professions do you have ? And which one(s) ?

**Comment by Imiona** [comment]
Reinstalled the Addon and now the Error is gone, dont ask me why, but sometimes this helps :p
