### ISSUE TITLE
Lua error when hovering over friends list

### ISSUE THREAD

**Issue by Chordbreak** [Mikeprod/XIV_Databar#48]
Hi, I'm getting the below lua error when hovering over the friends list icon:

Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:468: attempt to index field '?' (a nil value)
Time: 10/02/17 19:43:45
Count: 2
Stack: Interface\AddOns\XIV_Databar\modules\micromenu.lua:468: attempt to index field '?' (a nil value)
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
Interface\AddOns\XIV_Databar\modules\micromenu.lua:468: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:425>

Locals: errorMessage = "Interface\AddOns\XIV_Databar\modules\micromenu.lua:468: attempt to index field '?' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_

**Comment by Tradanel** [comment]
Hello there,

I've got the same problem with friend list : 


**Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:468: attempt to index field '?' (a nil value)
Time: 10/03/17 08:43:52
Count: 6
Stack: Interface\AddOns\XIV_Databar\modules\micromenu.lua:468: attempt to index field '?' (a nil value)
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
Interface\AddOns\XIV_Databar\modules\micromenu.lua:468: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:425>

Locals: errorMessage = "Interface\AddOns\XIV_Databar\modules\micromenu.lua:468: attempt to index field '?' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0**

**Comment by Mikeprod** [comment]
Caused by the appearance of the BNet App on iOS an Android :(

**Comment by Mikeprod** [comment]
Releasing the fixing now should be up in about 1 hour tops !

**Comment by Tradanel** [comment]
Thanks mate :)
