### ISSUE TITLE
Lua errors when clicking Loot Specialisation

### ISSUE THREAD

**Issue by belazor** [Mikeprod/XIV_Databar#49]
> Message: Interface\AddOns\XIV_Databar\modules\talent.lua:345: attempt to index field 'color' (a nil value)
Time: 10/08/17 00:20:44
Count: 4
Stack: Interface\AddOns\XIV_Databar\modules\talent.lua:345: attempt to index field 'color' (a nil value)
[C]: ?
Interface\AddOns\XIV_Databar\modules\talent.lua:345: in function <Interface\AddOns\XIV_Databar\modules\talent.lua:344>

> Message: Interface\AddOns\XIV_Databar\modules\talent.lua:349: attempt to index field 'color' (a nil value)
Time: 10/08/17 00:21:47
Count: 9
Stack: Interface\AddOns\XIV_Databar\modules\talent.lua:349: attempt to index field 'color' (a nil value)
[C]: ?
Interface\AddOns\XIV_Databar\modules\talent.lua:349: in function <Interface\AddOns\XIV_Databar\modules\talent.lua:348>

**Comment by Mikeprod** [comment]
Hello could you provide a screenshot of your bar please ? Jus to see the color you're using.

**Comment by Mikeprod** [comment]
Bumping this issue, to know if the big is still there.
