### ISSUE TITLE
Initialization? Lib?

### ISSUE THREAD

**Issue by cysteve** [Mikeprod/XIV_Databar#51]
Message: Interface\AddOns\XIV_Databar\core.lua:6: Cannot find a library instance of "LibDataBroker-1.1".
Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:14: attempt to index field 'constants' (a nil value)
Message: Interface\AddOns\XIV_Databar\modules\armor.lua:13: attempt to index field 'constants' (a nil value)
...

I get 16 of these messages on a fresh wow install. No other addons. brand new installs. Tried fresh wow 3 times. no ingame bar,  no config menu while addon is enabled. (show lua errors enabled)
If i install it with my other 200 addons together,  then i get bar and config. 

Full first error:

Message: Interface\AddOns\XIV_Databar\core.lua:6: Cannot find a library instance of "LibDataBroker-1.1".
Time: 10/30/17 06:25:06
Count: 1
Stack: Interface\AddOns\XIV_Databar\core.lua:6: Cannot find a library instance of "LibDataBroker-1.1".
[C]: ?
[C]: in function `error'
...nterface\AddOns\XIV_Databar\Libs\LibStub\LibStub.lua:23: in function `GetLibrary'
Interface\AddOns\XIV_Databar\core.lua:6: in main chunk

Locals:

**Comment by Mikeprod** [comment]
Ah just by reading my code, I see that the library is included with the add-on, but not attached to the core.lua. I'll push a fix this evening. Thanks
