### ISSUE TITLE
Order hall datatext?

### ISSUE THREAD

**Issue by Axiphel** [Mikeprod/XIV_Databar#6]
It'd be cool if there was a button for the order hall menu (that is usually brought up with the minimap button) that showed all the information like Nomi work orders and stuff on mouseover.

**Comment by Mikeprod** [comment]
I don't know what to do about it ...

**Comment by Mikeprod** [comment]
It concerns the LDB support requested on the issue #1 I am working on it. Otherwise you have an addon called Broker: Garrison that does it too ;)
