### ISSUE TITLE
8.0.1 crashes

### ISSUE THREAD

**Issue by eaglegoboom** [Mikeprod/XIV_Databar#61]
any plans to update this for BfA?

so when I log in to game, xiv_databar has just a constant streaming of errors before my game locks up and freezes.

by chance does it send it to a log I can upload?

**Comment by Mikeprod** [comment]
Yes, if you do not detail anything, I do not know what's wong. I did not have any beta access.

**Comment by Kraznan** [comment]
This is what I am getting.

Message: Interface\AddOns\XIV_Databar\modules\travel.lua:444: attempt to call global 'GetMapNameByID' (a nil value)
Time: Tue Jul 17 20:08:58 2018
Count: 1
Stack: Interface\AddOns\XIV_Databar\modules\travel.lua:444: attempt to call global 'GetMapNameByID' (a nil value)
Interface\AddOns\XIV_Databar\modules\travel.lua:444: in function `FindFirstOption'
Interface\AddOns\XIV_Databar\modules\travel.lua:461: in function `GetDefaultOptions'
Interface\AddOns\XIV_Databar\core.lua:114: in function <Interface\AddOns\XIV_Databar\core.lua:80>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

**Comment by Kraznan** [comment]
Message: Interface\AddOns\XIV_Databar\modules\gold.lua:81: attempt to call global 'CalendarGetDate' (a nil value)
Time: Tue Jul 17 20:08:58 2018
Count: 1
Stack: Interface\AddOns\XIV_Databar\modules\gold.lua:81: attempt to call global 'CalendarGetDate' (a nil value)
Interface\AddOns\XIV_Databar\modules\gold.lua:81: in function <Interface\AddOns\XIV_Databar\modules\gold.lua:70>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

There are 10 in total.

**Comment by Kraznan** [comment]
Message: Interface\AddOns\XIV_Databar\modules\armor.lua:115: attempt to index field 'armor' (a nil value)
Time: Tue Jul 17 20:08:59 2018
Count: 1
Stack: Interface\AddOns\XIV_Databar\modules\armor.lua:115: attempt to index field 'armor' (a nil value)
Interface\AddOns\XIV_Databar\modules\armor.lua:115: in function `Refresh'
Interface\AddOns\XIV_Databar\core.lua:317: in function `Refresh'
Interface\AddOns\XIV_Databar\modules\armor.lua:37: in function <Interface\AddOns\XIV_Databar\modules\armor.lua:29>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:564: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1187: in function <Interface\FrameXML\UIParent.lua:1085>

Locals: <none>

**Comment by Kraznan** [comment]
Message: ...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "TRADE_SKILL_UPDATE"
Time: Tue Jul 17 20:08:59 2018
Count: 1
Stack: ...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "TRADE_SKILL_UPDATE"
[C]: in function `RegisterEvent'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:33: in function `OnUsed'
...ils\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:168: in function `RegisterEvent'
Interface\AddOns\XIV_Databar\modules\tradeskill.lua:176: in function `RegisterFrameEvents'
Interface\AddOns\XIV_Databar\modules\tradeskill.lua:41: in function <Interface\AddOns\XIV_Databar\modules\tradeskill.lua:28>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:564: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1187: in function <Interface\FrameXML\UIParent.lua:1085>

Locals: <none>

**Comment by Kraznan** [comment]
Message: Interface\AddOns\XIV_Databar\modules\system.lua:36: attempt to index field 'system' (a nil value)
Time: Tue Jul 17 20:08:59 2018
Count: 1
Stack: Interface\AddOns\XIV_Databar\modules\system.lua:36: attempt to index field 'system' (a nil value)
Interface\AddOns\XIV_Databar\modules\system.lua:36: in function `Refresh'
Interface\AddOns\XIV_Databar\modules\system.lua:25: in function <Interface\AddOns\XIV_Databar\modules\system.lua:16>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:564: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1187: in function <Interface\FrameXML\UIParent.lua:1085>

Locals: <none>

**Comment by Kraznan** [comment]
Message: Interface\AddOns\XIV_Databar\modules\armor.lua:115: attempt to index field 'armor' (a nil value)
Time: Tue Jul 17 20:11:40 2018
Count: 24
Stack: Interface\AddOns\XIV_Databar\modules\armor.lua:115: attempt to index field 'armor' (a nil value)
(tail call): ?
Interface\AddOns\XIV_Databar\modules\armor.lua:115: in function `Refresh'
Interface\AddOns\XIV_Databar\modules\armor.lua:151: in function `?'
...ils\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ils\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ils\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Kraznan** [comment]
Message: ...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:283: attempt to call upvalue 'GetNumPurchasableTraits' (a nil value)
Time: Tue Jul 17 20:09:02 2018
Count: 1
Stack: ...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:283: attempt to call upvalue 'GetNumPurchasableTraits' (a nil value)
[C]: ?
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:283: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:274>
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:308: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:304>
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:373: in function `?'
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:69: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:69>

Locals:

**Comment by Kraznan** [comment]
Message: Interface\AddOns\XIV_Databar\modules\system.lua:36: attempt to index field 'system' (a nil value)
Time: Tue Jul 17 20:11:59 2018
Count: 6392
Stack: Interface\AddOns\XIV_Databar\modules\system.lua:36: attempt to index field 'system' (a nil value)
[C]: ?
Interface\AddOns\XIV_Databar\modules\system.lua:36: in function `Refresh'
Interface\AddOns\XIV_Databar\modules\system.lua:259: in function <Interface\AddOns\XIV_Databar\modules\system.lua:253>

Locals:

**Comment by Kraznan** [comment]
Message: Interface\AddOns\XIV_Databar\modules\clock.lua:116: attempt to call global 'CalendarGetNumPendingInvites' (a nil value)
Time: Tue Jul 17 20:12:06 2018
Count: 6701
Stack: Interface\AddOns\XIV_Databar\modules\clock.lua:116: attempt to call global 'CalendarGetNumPendingInvites' (a nil value)
[C]: in function `CalendarGetNumPendingInvites'
Interface\AddOns\XIV_Databar\modules\clock.lua:116: in function <Interface\AddOns\XIV_Databar\modules\clock.lua:103>

Locals:

**Comment by eaglegoboom** [comment]
sorry about the lack of data on my part Mikeprod, the error rate just for xiv_databar goes to over 3k in just a few seconds of logging in. does it send the error to a log? can I send it to a log?

had i known you didnt have beta access I could have fixed that.

**Comment by Mikeprod** [comment]
No worries, I will post the hotfixes tonight. Thanks for your feedback

**Comment by DustyMiles** [comment]
Thanks for the addon first off. I really like it and the look. I see your posting update tonight but this is more of a general question. Is there a /command to open the options?

**Comment by Mikeprod** [comment]
/xb or /xivbar will do the same thing and toggle the config

**Comment by eaglegoboom** [comment]
Awesome thanks Mike 


Sent from my Sprint Samsung Galaxy Note8.
-------- Original message --------From: Mikeprod <notifications@github.com> Date: 7/18/18  2:37 PM  (GMT-05:00) To: Mikeprod/XIV_Databar <XIV_Databar@noreply.github.com> Cc: eaglegoboom <jjonessec@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Mikeprod/XIV_Databar] 8.0.1 crashes (#61) 
It should all be fixed now, leaving it open for a day or 2

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Mikeprod/XIV_Databar","title":"Mikeprod/XIV_Databar","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Mikeprod/XIV_Databar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Mikeprod in #61: It should all be fixed now, leaving it open for a day or 2"}],"action":{"name":"View Issue","url":"https://github.com/Mikeprod/XIV_Databar/issues/61#issuecomment-406032437"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Mikeprod/XIV_Databar/issues/61#issuecomment-406032437",
"url": "https://github.com/Mikeprod/XIV_Databar/issues/61#issuecomment-406032437",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Mikeprod/XIV_Databar] 8.0.1 crashes (#61)",
"sections": [
{
"text": "",
"activityTitle": "**Mikeprod**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Mikeprod",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Mikeprod/XIV_Databar\",\n\"issueId\": 61,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Mikeprod/XIV_Databar\",\n\"issueId\": 61\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Mikeprod/XIV_Databar/issues/61#issuecomment-406032437"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 357405584\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Pelani** [comment]
Thank you for the great work. I was getting a little antsy not having those icons on the bottom of my screen. lol

**Comment by Mikeprod** [comment]
So far so good, I am closing this issue
