### ISSUE TITLE
Error lua, pls help

### ISSUE THREAD

**Issue by Kheryon** [Mikeprod/XIV_Databar#66]
Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:663: attempt to call global 'ChatFrame_OpenMenu' (a nil value)
Time: Wed Aug  1 14:57:14 2018
Count: 4
Stack: Interface\AddOns\XIV_Databar\modules\micromenu.lua:663: attempt to call global 'ChatFrame_OpenMenu' (a nil value)
Interface\AddOns\XIV_Databar\modules\micromenu.lua:663: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:657>

Locals: self = chat {
 0 = <userdata>
}
button = "LeftButton"
down = false
(*temporary) = nil
(*temporary) = "attempt to call global 'ChatFrame_OpenMenu' (a nil value)"
xb = <table> {
 defaults = <table> {
 }
 ResetUI = <function> defined @Interface\AddOns\XIV_Databar\core.lua:391
 HoverColors = <function> defined @Interface\AddOns\XIV_Databar\core.lua:172
 HexToRGBA = <function> defined @Interface\AddOns\XIV_Databar\core.lua:338
 modules = <table> {
 }
 baseName = "XIV_Databar"
 IterateEmbeds = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 GetColor = <function> defined @Interface\AddOns\XIV_Databar\core.lua:167
 fontFlags = <table> {
 }
 GetTextColorOptions = <function> defined @Interface\AddOns\XIV_Databar\core.lua:602
 RegisterFrame = <function> defined @Interface\AddOns\XIV_Databar\core.lua:190
 Printf = <function> defined @Interface\AddOns\Dominos\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 GetHeight = <function> defined @Interface\AddOns\XIV_Databar\core.lua:270
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 DisableModule = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 GetFont = <function> defined @Interface\AddOns\XIV_Databar\core.lua:321
 PrintTable = <function> defined @Interface\AddOns\XIV_Databar\core.lua:346
 RegisterMessage = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 GetArgs = <function> defined @Interface\AddOns\Dominos\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 frames = <table> {
 }
 miniTextPosition = "BOTTOM"
 db = <table> {
 }
 modulesOptionFrame = <unnamed> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 IterateModules = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 GetClassColors = <function> defined @Interface\AddOns\XIV_Databar\core.lua:325
 SetColor = <function> defined @Interface\AddOns\XIV_Databar\core.lua:158
 OnInitialize = <function> defined @Interface\AddOns\XIV_Databar\core.lua:80
 NewModule = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 GetModule = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:241
 defaultModuleLibraries = <table> {
 }
 optionsFrame = <unnamed> {
 }
 GetTextOptions = <function> defined @Interface\AddOns\XIV_Databar\core.lua:546
 UnregisterChatCommand = <function> defined @Interface\AddOns\Dominos\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 GetName = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 name = "XIV_Databar"
 HideBarEvent = <function> defined @Interface\AddOns\XIV_Databar\core.lua:211
 orderedModules = <table> {
 }
 CreateMainBar = <function> defined @Interface\AddOns\XIV_Databar\core.lua:204
 Disable = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:345
 LSM = <table> {
 }
 Print = <function> defined @Interface\AddOns\Dominos\libs\AceConsole-3.0\AceConsole-3.0.lua:

**Comment by Mikeprod** [comment]
Yes indeed the function has changed. Will be fixed in a future release
