### ISSUE TITLE
Attempt to unregister unknown event "ARTIFACT_MAX_RANKS_UPDATE"

### ISSUE THREAD

**Issue by katur239** [Mikeprod/XIV_Databar#68]
Cannot open Artifact by shift right clicking or use the artifact forge thing. 

Message: ...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:510: Attempt to unregister unknown event "ARTIFACT_MAX_RANKS_UPDATE"
Time: Sun Aug  5 01:16:04 2018
Count: 1
Stack: ...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:510: Attempt to unregister unknown event "ARTIFACT_MAX_RANKS_UPDATE"
[C]: in function `UnregisterEvent'
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:510: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:502>
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:723: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:721>
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:1004: in function `ForceUpdate'
Interface\AddOns\XIV_Databar\modules\talent.lua:68: in function <Interface\AddOns\XIV_Databar\modules\talent.lua:55>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...\AddOns\CollectMe\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...\AddOns\CollectMe\Libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...\AddOns\CollectMe\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...\AddOns\CollectMe\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:564: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1191: in function <Interface\FrameXML\UIParent.lua:1089>

Locals: <none>

**Comment by Mikeprod** [comment]
Should be fixed in the latest release. Please confirm and close the issue.

**Comment by katur239** [comment]
Fixed. Thanks!
