### ISSUE TITLE
ElvUI and Databar

### ISSUE THREAD

**Issue by Imiona** [Mikeprod/XIV_Databar#7]
Hello

For some (weird) Reason, XIV Databar prevents the clicking of Chatchannels when ElvUI is installed. Maybe you could look into this?

Thx

**Comment by Mikeprod** [comment]
I have to install ElvUI for that.... You happy ? XD

**Comment by Mikeprod** [comment]
Can you screenshot the problem ? I cannot see what's wrong ....

**Comment by Imiona** [comment]
Here you go https://www.youtube.com/watch?v=4QOzgf33X60

**Comment by Imiona** [comment]
Fixed, a reinstall of WOW did the trick, dont  ask me why^^

**Comment by Mikeprod** [comment]
Glad to hear it is fixed :D
