### ISSUE TITLE
talent.lua error (when hovering over the spec)

### ISSUE THREAD

**Issue by grimmel95** [Mikeprod/XIV_Databar#73]
Looks like this is specific to characters that have an artifact weapon. I logged in on some lower level characters and the error does not appear.

version: b2.0.17-32-g371aab7

Message: Interface\AddOns\XIV_Databar\modules\talent.lua:541: attempt to call method 'GetArtifactKnowledge' (a nil value)
Time: Thu Aug  9 08:22:09 2018
Count: 1
Stack: Interface\AddOns\XIV_Databar\modules\talent.lua:541: attempt to call method 'GetArtifactKnowledge' (a nil value)
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574>
[C]: in function `GetArtifactKnowledge'
Interface\AddOns\XIV_Databar\modules\talent.lua:541: in function `ShowTooltip'
Interface\AddOns\XIV_Databar\modules\talent.lua:234: in function <Interface\AddOns\XIV_Databar\modules\talent.lua:229>

Locals: errMsg = "Interface\AddOns\XIV_Databar\modules\talent.lua:541: attempt to call method 'GetArtifactKnowledge' (a nil value)"
errorTime = 1531255461.5504
tsmErrMsg = nil
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:378
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:105
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:355
 SantizeErrorReportString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:386
 errorFrame = <unnamed> {
 }
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

**Comment by grimmel95** [comment]
Looks like this is specific to characters that have an artifact weapon. I logged in on some lower level characters and the error does not appear.

**Comment by Mikeprod** [comment]
Duplicate #71

**Comment by Mikeprod** [comment]
Thank you for your time reporting the issue, sorry for being abrupt on closing this issue.
