### ISSUE TITLE
Lua error micromenu.lua nil value

### ISSUE THREAD

**Issue by skmzarn** [Mikeprod/XIV_Databar#79]
All of a sudden, my social module stopped working when mouseover the icon. I get this error now:

> 1x XIV_Databar\modules\micromenu.lua:470: attempt to index field '?' (a nil value)
> XIV_Databar\modules\micromenu.lua:470: in function <XIV_Databar\modules\micromenu.lua:426>
> 
> Locals:
> modifierFunc = <function> defined =[C]:-1
> tooltip = <unnamed> {
>  0 = <userdata>
>  lines = <table> {
>  }
>  columns = <table> {
>  }
>  key = "SocialToolTip"
>  scrollChild = <unnamed> {
>  }
>  colspans = <table> {
>  }
>  width = 481.73071289063
>  cell_margin_h = 6
>  regularFont = GameTooltipText {
>  }
>  labelProvider = <table> {
>  }
>  scripts = <table> {
>  }
>  height = 291.98671913147
>  headerFont = GameTooltipHeaderText {
>  }
>  cell_margin_v = 3
>  scrollFrame = <unnamed> {
>  }
> }
> totalBNFriends = 59
> totalBNOnlineFriends = 29
> totalFriends = 1
> totalOnlineFriends = 0
> charNameFormat = ""
> clientsList = <table> {
>  1 = "WoW"
>  2 = "S2"
>  3 = "D3"
>  4 = "WTCG"
>  5 = "Hero"
>  6 = "Pro"
>  7 = "S1"
>  8 = "DST2"
>  9 = "VIPR"
> }
> (for index) = 15
> (for limit) = 59
> (for step) = 1
> i = 15
> battleID = 45
> battleName = "|Kf46|k0000000|k"
> battleTag = "xxxxxxxxxxx"
> _ = true
> charName = nil
> gameAccount = 118
> gameClient = "VIPR"
> isOnline = true
> _ = 1537031928
> isAfk = false
> isDnd = false
> _ = ""
> note = ""
> _ = true
> _ = ""
> _ = "VIPR"
> realmName = ""
> _ = 0
> status = "Online"
> statusIcon = "FriendsFrame\StatusIcon-Online"
> socialIcon = "FriendsFrame\Battlenet-CallOfDutyBlackOps4icon"
> (*temporary) = nil
> (*temporary) = "FriendsFrame\Battlenet-CallOfDutyBlackOps4icon"
> (*temporary) = ""
> (*temporary) = ""
> (*temporary) = ""
> (*temporary) = "In Lobby, Duos selected | Blackout"
> (*temporary) = ""
> (*temporary) = 0
> (*temporary) = "attempt to index field '?' (a nil value)"
> xb = <table> {
>  defaults = <table> {
>  }
>  ResetUI = <function> defined @XIV_Databar\core.lua:391
>  HoverColors = <function> defined @XIV_Databar\core.lua:172
>  HexToRGBA = <function> defined @XIV_Databar\core.lua:338
>  modules = <table> {
>  }
>  baseName = "XIV_Databar"
>  IterateEmbeds = <function> defined @ACU\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
>  GetColor = <function> defined @XIV_Databar\core.lua:167
>  fontFlags = <table> {
>  }
>  GetTextColorOptions = <function> defined @XIV_Databar\core.lua:602
>  RegisterFrame = <function> defined @XIV_Databar\core.lua:190
>  Printf = <function> defined @ACU\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
>  SetDefaultModulePrototype = <function> defined @ACU\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
>  GetHeight = <function> defined @XIV_Databar\core.lua:270
>  defaultModuleState = true
>  IsEnabled = <function> defined @ACU\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
>  DisableModule = <function> defined @ACU\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
>  GetFont = <function> defined @XIV_Databar\core.lua:321
>  PrintTable = <function> defined @XIV_Databar\core.lua:346
>  RegisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
>  GetArgs = <function> defined @ACU\Libs\AceConsole-3.0\AceConsole-3.0.lua:144
>  frames = <table> {
>  }
>  miniTextPosition = "BOTTOM"
>  db = <table> {
>  }
>  modulesOptionFrame = <unnamed> {
>  }
>  SetEnabledState = <function> defined @ACU\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
>  enabledState = true
>  RegisterEvent = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
>  IterateModules = <function> defined @ACU\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
>  GetClassColors = <function> defined @XIV_Databar\core.lua:325
>  SetColor = <function> defined @XIV_Databar\core.lua:158
>  OnInitialize = <function> defined @XIV_Databar\core.lua:80
>  NewModule = <function> defined @ACU\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
>  GetModule = <function> defined @ACU\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
>  defaultModuleLibraries = <table> {
>  }
>  optionsFrame = <unnamed> {
>  }
>  GetTextOptions = <function> defined @XIV_Databar\core.lua:546
>  UnregisterChatCommand = <function> defined @ACU\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
>  GetName

**Comment by Mikeprod** [comment]
duplicate #84
