### ISSUE TITLE
About whisper and invite...

### ISSUE THREAD

**Issue by yaoenqi** [Mikeprod/XIV_Databar#8]
When I click on a Guild Member, the chat input box will display "PlayerName -RealmName -RealmName" and then I whisper to player, the system prompts: Not found online player named "PlayerName -RealmName -RealmName".When I hold down the SHIFT key and click on a Guild Member to invite him, the system prompts: you cannot invite the player from this realm.

**Comment by Mikeprod** [comment]
Uhm, I need a guild to test that :D there is really twice the realmName ?

**Comment by yaoenqi** [comment]
yep...

**Comment by Mikeprod** [comment]
Can you just change the line 598 in the micromenu module to `if not name:find('%u%U*-%u%U*') then` to see if it still does that ?

**Comment by yaoenqi** [comment]
I tried but it still doesn't work.

**Comment by Mikeprod** [comment]
The problem happens with only the Chinese locale ?

**Comment by Mikeprod** [comment]
What about commenting the whole if block starting line 598 ... ?

**Comment by yaoenqi** [comment]
Sorry,I don't know.But I've changed the line 601 to  `name=name--.."-"..homeRealm`. It is running correctly.

**Comment by Mikeprod** [comment]
According to the documentation this block should be useless

**Comment by yaoenqi** [comment]
After I changed the line 601, I tried to whisper to myself and invite myself. Now everything is OK.
