### ISSUE TITLE
Lua error on mousing over battle.net friends on bar

### ISSUE THREAD

**Issue by Emarline** [Mikeprod/XIV_Databar#82]
The dropdown also doesn't show - just throws this error:

100x XIV_Databar\modules\micromenu.lua:470: attempt to index field '?' (a nil value)
XIV_Databar\modules\micromenu.lua:470: in function <XIV_Databar\modules\micromenu.lua:426>

Locals:
modifierFunc = <function> defined =[C]:-1
tooltip = <unnamed> {
 0 = <userdata>
 lines = <table> {
 }
 headerFont = GameTooltipHeaderText {
 }
 cell_margin_v = 3
 key = "SocialToolTip"
 scripts = <table> {
 }
 columns = <table> {
 }
 scrollFrame = <unnamed> {
 }
 template = "Transparent"
 scrollChild = <unnamed> {
 }
 colspans = <table> {
 }
 width = 518.9776763916
 cell_margin_h = 6
 labelProvider = <table> {
 }
 height = 779.8761844635
 regularFont = GameTooltipText {
 }
}
totalBNFriends = 107
totalBNOnlineFriends = 72
totalFriends = 0
totalOnlineFriends = 0
charNameFormat = ""
clientsList = <table> {
 1 = "WoW"
 2 = "S2"
 3 = "D3"
 4 = "WTCG"
 5 = "Hero"
 6 = "Pro"
 7 = "S1"
 8 = "DST2"
 9 = "VIPR"
}
(for index) = 45
(for limit) = 107
(for step) = 1
i = 45
battleID = 82
battleName = "|Kf81|k000000000|k"
battleTag = "Killerpox#1990"
_ = true
charName = nil
gameAccount = 359
gameClient = "VIPR"
isOnline = true
_ = 1536978705
isAfk = false
isDnd = false
_ = "I'm back, if people care."
note = "#Friends"
_ = true
_ = ""
_ = "VIPR"
realmName = ""
_ = 0
status = "Online"
statusIcon = "FriendsFrame\StatusIcon-Online"
socialIcon = "FriendsFrame\Battlenet-CallOfDutyBlackOps4icon"
(*temporary) = nil
(*temporary) = "FriendsFrame\Battlenet-CallOfDutyBlackOps4icon"
(*temporary) = ""
(*temporary) = ""
(*temporary) = ""
(*temporary) = "In Lobby, Solo selected | Blackout"
(*temporary) = "I'm back, if people care."
(*temporary) = 1533179879
(*temporary) = "attempt to index field '?' (a nil value)"
xb = <table> {
 defaults = <table> {
 }
 ResetUI = <function> defined @XIV_Databar\core.lua:391
 HoverColors = <function> defined @XIV_Databar\core.lua:172
 HexToRGBA = <function> defined @XIV_Databar\core.lua:338
 modules = <table> {
 }
 baseName = "XIV_Databar"
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:473
 GetColor = <function> defined @XIV_Databar\core.lua:167
 fontFlags = <table> {
 }
 GetTextColorOptions = <function> defined @XIV_Databar\core.lua:602
 RegisterFrame = <function> defined @XIV_Databar\core.lua:190
 Printf = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:440
 GetHeight = <function> defined @XIV_Databar\core.lua:270
 defaultModuleState = true
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:482
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:381
 GetFont = <function> defined @XIV_Databar\core.lua:321
 PrintTable = <function> defined @XIV_Databar\core.lua:346
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 GetArgs = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:144
 frames = <table> {
 }
 miniTextPosition = "BOTTOM"
 db = <table> {
 }
 modulesOptionFrame = <unnamed> {
 }
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:455
 enabledState = true
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:468
 GetClassColors = <function> defined @XIV_Databar\core.lua:325
 SetColor = <function> defined @XIV_Databar\core.lua:158
 OnInitialize = <function> defined @XIV_Databar\core.lua:80
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:266
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:241
 defaultModuleLibraries = <table> {
 }
 optionsFrame = <unnamed> {
 }
 GetTextOptions = <function> defined @XIV_Databar\core.lua:546
 UnregisterChatCommand = <function> defined @Ace3\AceCons

**Comment by Mikeprod** [comment]
The error indeed showed directly how to fix it. I should be fxed in commit 985895b
