### ISSUE TITLE
Can't open bags in combat

### ISSUE THREAD

**Issue by Orlyy0056** [Mikeprod/XIV_Databar#92]
This happens for EVERY panel on your bar now :(, it works fine if I am out of combat.

**Comment by randompsique** [comment]
yeah with patch 8.2 it doesn't work in combat anymore :( not the micromenu at least.

**Comment by Mikeprod** [comment]
Hi, apparently it does not come from the addon itself but the Blizzard UI itself. Even Weak Aura is having the same issue : https://twitter.com/WeakAuras/status/1146728718053904385
