### ISSUE TITLE
Social Menu Errors

### ISSUE THREAD

**Issue by calskica** [Mikeprod/XIV_Databar#95]
Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:485: attempt to concatenate local 'realmName' (a nil value)
Time: Fri Oct 11 16:18:23 2019
Count: 8
Stack: Interface\AddOns\XIV_Databar\modules\micromenu.lua:485: attempt to concatenate local 'realmName' (a nil value)
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:582: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:542>
[C]: ?
Interface\AddOns\XIV_Databar\modules\micromenu.lua:485: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:429>

Locals: errMsg = "Interface\AddOns\XIV_Databar\modules\micromenu.lua:485: attempt to concatenate local 'realmName' (a nil value)"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:334
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:116
 hitInternalError = false
 errorFrame = <unnamed> {
 }
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:349
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:342
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:312
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:280
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

**Comment by Jkeller662** [comment]
Message: Interface\AddOns\XIV_Databar\modules\micromenu.lua:485: attempt to concatenate local 'realmName' (a nil value)
Time: Sat Mar 28 23:49:19 2020
Count: 2
Stack: Interface\AddOns\XIV_Databar\modules\micromenu.lua:485: attempt to concatenate local 'realmName' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\XIV_Databar\modules\micromenu.lua"]:485: in function <Interface\AddOns\XIV_Databar\modules\micromenu.lua:429>

Locals:
