### ISSUE TITLE
8.3

### ISSUE THREAD

**Issue by bowencz** [Mikeprod/XIV_Databar#96]
87x XIV_Databar\modules\micromenu.lua:485: attempt to concatenate local 'realmName' (a nil value)
XIV_Databar\modules\micromenu.lua:485: in function <XIV_Databar\modules\micromenu.lua:429>

Locals:
modifierFunc = <function> defined =[C]:-1
tooltip = <unnamed> {
 0 = <userdata>
 regularFont = GameTooltipText {
 }
 columns = <table> {
 }
 scrollChild = <unnamed> {
 }
 colspans = <table> {
 }
 cell_margin_v = 3
 width = 61.000004
 headerFont = GameTooltipHeaderText {
 }
 cell_margin_h = 6
 key = "SocialToolTip"
 scripts = <table> {
 }
 height = 30.999998
 labelProvider = <table> {
 }
 lines = <table> {
 }
 scrollFrame = <unnamed> {
 }
}
totalBNFriends = 132
totalBNOnlineFriends = 57
totalFriends = 30
totalOnlineFriends = 1
charNameFormat = nil
clientsList = <table> {
 1 = "WoW"
 2 = "S2"
 3 = "D3"
 4 = "WTCG"
 5 = "Hero"
 6 = "Pro"
 7 = "S1"
 8 = "DST2"
 9 = "VIPR"
}
(for index) = 1
(for limit) = 132
(for step) = 1
i = 1
battleID = 56
battleName = "|Kq33|k"
battleTag = "Tera#2822"
_ = false
charName = "Desireu"
gameAccount = 174
gameClient = "WoW"
isOnline = true
_ = 1578558235
isAfk = false
isDnd = false
_ = ""
note = ""
_ = nil
_ = nil
_ = nil
realmName = nil
_ = nil
status = "Online"
statusIcon = "FriendsFrame\StatusIcon-Online"
socialIcon = "FriendsFrame\Battlenet-WoWicon"
gameName = "World of Warcraft"
(*temporary) = "(|cffecd672"
(*temporary) = "Desireu"
(*temporary) = "-"
(*temporary) = nil
(*temporary) = "|r)"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'realmName' (a nil value)"
xb = <table> {
 defaults = <table> {
 }
 ResetUI = <function> defined @XIV_Databar\core.lua:391
 HoverColors = <function> defined @XIV_Databar\core.lua:172
 HexToRGBA = <function> defined @XIV_Databar\core.lua:338
 modules = <table> {
 }
 baseName = "XIV_Databar"
 IterateEmbeds = <function> defined @AdvancedTooltips\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 GetColor = <function> defined @XIV_Databar\core.lua:167
 fontFlags = <table> {
 }
 GetTextColorOptions = <function> defined @XIV_Databar\core.lua:602
 RegisterFrame = <function> defined @XIV_Databar\core.lua:190
 Printf = <function> defined @AdvancedTooltips\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @AdvancedTooltips\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 GetHeight = <function> defined @XIV_Databar\core.lua:270
 defaultModuleState = true
 IsEnabled = <function> defined @AdvancedTooltips\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 DisableModule = <function> defined @AdvancedTooltips\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 GetFont = <function> defined @XIV_Databar\core.lua:321
 PrintTable = <function> defined @XIV_Databar\core.lua:346
 RegisterMessage = <function> defined @AdvancedTooltips\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @AdvancedTooltips\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 frames = <table> {
 }
 miniTextPosition = "BOTTOM"
 db = <table> {
 }
 modulesOptionFrame = <unnamed> {
 }
 SetEnabledState = <function> defined @AdvancedTooltips\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 enabledState = true
 RegisterEvent = <function> defined @AdvancedTooltips\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IterateModules = <function> defined @AdvancedTooltips\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 GetClassColors = <function> defined @XIV_Databar\core.lua:325
 SetColor = <function> defined @XIV_Databar\core.lua:158
 OnInitialize = <function> defined @XIV_Databar\core.lua:80
 NewModule = <function> defined @AdvancedTooltips\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 GetModule = <function> defined @AdvancedTooltips\libs\AceAddon-3.0\AceAddon-3.0.lua:241
 defaultModuleLibraries = <table> {
 }
 optionsFrame = <unnamed> {
 }
 GetTextOptions = <function> defined @XIV_Databar\core.lua:546
 UnregisterChatCommand = <function> def

**Comment by FullSol** [comment]
Similar issue:

`2x XIV_Databar\modules\micromenu.lua:485: attempt to concatenate local 'realmName' (a nil value)
[string "@XIV_Databar\modules\micromenu.lua"]:485: in function <XIV_Databar\modules\micromenu.lua:429>

Locals:
modifierFunc = <function> defined =[C]:-1
tooltip = <unnamed> {
 0 = <userdata>
 lines = <table> {
 }
 PixelSnapDisabled = true
 headerFont = GameTooltipHeaderText {
 }
 key = "SocialToolTip"
 scripts = <table> {
 }
 SetBackdropBorderColor = <function> defined =[C]:-1
 scrollFrame = <unnamed> {
 }
 template = "Transparent"
 cell_margin_v = 3
 scrollChild = <unnamed> {
 }
 colspans = <table> {
 }
 columns = <table> {
 }
 width = 180.960419
 cell_margin_h = 6
 labelProvider = <table> {
 }
 regularFont = GameTooltipText {
 }
 height = 132.920460
 SetBackdropColor = <function> defined =[C]:-1
 pixelBorders = <table> {
 }
}
totalBNFriends = 100
totalBNOnlineFriends = 36
totalFriends = 0
totalOnlineFriends = 0
charNameFormat = ""
clientsList = <table> {
 1 = "WoW"
 2 = "S2"
 3 = "D3"
 4 = "WTCG"
 5 = "Hero"
 6 = "Pro"
 7 = "S1"
 8 = "DST2"
 9 = "VIPR"
}
(for index) = 9
(for limit) = 100
(for step) = 1
i = 9
battleID = 71
battleName = "|Kq51|k"
battleTag = "Aearowen#1979"
_ = true
charName = "Föxì"
gameAccount = 107
gameClient = "WoW"
isOnline = true
_ = 1586874028
isAfk = false
isDnd = false
_ = "WE SET A DATE!!!!!! <3 <3 <3 <3"
note = ""
_ = nil
_ = nil
_ = nil
realmName = nil
_ = nil
status = "Online"
statusIcon = "FriendsFrame\StatusIcon-Online"
socialIcon = "FriendsFrame\Battlenet-WoWicon"
gameName = "World of Warcraft"
(*temporary) = "(|cffecd672"
(*temporary) = "Föxì"
(*temporary) = "-"
(*temporary) = nil
(*temporary) = "|r)"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'realmName' (a nil value)"
xb = <table> {
 defaults = <table> {
 }
 ResetUI = <function> defined @XIV_Databar\core.lua:391
 HoverColors = <function> defined @XIV_Databar\core.lua:172
 HexToRGBA = <function> defined @XIV_Databar\core.lua:338
 modules = <table> {
 }
 baseName = "XIV_Databar"
 IterateEmbeds = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 GetColor = <function> defined @XIV_Databar\core.lua:167
 fontFlags = <table> {
 }
 GetTextColorOptions = <function> defined @XIV_Databar\core.lua:602
 RegisterFrame = <function> defined @XIV_Databar\core.lua:190
 Printf = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 GetHeight = <function> defined @XIV_Databar\core.lua:270
 defaultModuleState = true
 IsEnabled = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 DisableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 GetFont = <function> defined @XIV_Databar\core.lua:321
 PrintTable = <function> defined @XIV_Databar\core.lua:346
 RegisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 frames = <table> {
 }
 miniTextPosition = "BOTTOM"
 db = <table> {
 }
 modulesOptionFrame = <unnamed> {
 }
 SetEnabledState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 RegisterEvent = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IterateModules = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 GetClassColors = <function> defined @XIV_Databar\core.lua:325
 SetColor = <function> defined @XIV_Databar\core.lua:158
 OnInitialize = <function> defined @XIV_Databar\core.lua:80
 NewModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 defaultModuleLibraries = <table> {
 }
 optionsFrame = <unna`

**Comment by bsimms606** [comment]
I posted a pull request that fixed it for me, if you want to try that out in the mean time.
